# /**
#  * OpenArabDict
#  * Copyright (C) 2025-2026 Amir Czwink (amir130@hotmail.de)
#  * 
#  * This program is free software: you can redistribute it and/or modify
#  * it under the terms of the GNU Affero General Public License as published by
#  * the Free Software Foundation, either version 3 of the License, or
#  * (at your option) any later version.
#  * 
#  * This program is distributed in the hope that it will be useful,
#  * but WITHOUT ANY WARRANTY; without even the implied warranty of
#  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  * GNU Affero General Public License for more details.
#  * 
#  * You should have received a copy of the GNU Affero General Public License
#  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
#  * */
name: Translate dictionary to German

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and deploy to Azure"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  translate_dict:
    runs-on: ubuntu-latest
    name: Translate dictionary to German
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      #build domain
      - name: Building OpenArabDict domain
        run: |
          npm ci
          npm run build
        working-directory: ./domain

      #build translator
      - name: Building OpenArabDict translator
        run: |
          npm ci
          npm run build
        working-directory: ./translator

      #prepare translation
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download English dictionary
        run: |
          az storage blob download --file ./en.json --blob-url https://openarabdictdbstorage.blob.core.windows.net/dbstorage/en.json --auth-mode login --overwrite
        working-directory: ./

      - name: Deploy translation service
        id: deploy-translation-service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: openarabdict
          template: ./infrastructure/translator.bicep
          failOnStdErr: false

      - name: Wait for deployment of translation service
        run: |
          sleep 1m
        shell: bash

      #translate
      - name: Call OpenArabDict translator
        env:
          ARABDICT_TRANSLATIONSERVICE_KEY: ${{ steps.deploy-translation-service.outputs['cognitiveServiceKey'] }}
          ARABDICT_TRANSLATIONSERVICE_REGION: eastus
        run: |
          npm run run ../en.json de ../de.json
        working-directory: ./translator

      - name: Upload dict to Azure
        run: |
          az storage blob upload --file ./de.json --blob-url https://openarabdictdbstorage.blob.core.windows.net/dbstorage/de.json --auth-mode login --overwrite
        working-directory: ./

      #cleanup
      - name: Delete translation service
        run: |
          az resource delete --resource-group openarabdict --resource-type Microsoft.CognitiveServices/accounts --name openarabdict-translator
        #az resource delete --verbose --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/eastus/resourceGroups/openarabdict/deletedAccounts/openarabdict-translator

      - name: logout
        run: |
          az logout
