name: Translate dictionary to German

on:
  push:
    branches: [ "translation-pipeline" ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and deploy to Azure"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  translate_dict:
    runs-on: ubuntu-latest
    name: Translate dictionary to German
    env:
      RG_NAME: openarabdict-${{ github.run_id }}-${{ github.run_attempt }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      #Deploy translation service
      - name: Azure CLI Action
        uses: Azure/cli@v2.2.0
        with:
          inlineScript: az group create --name ${{ env.RG_NAME }} --location eastus
