name: Translate dictionary to German

on:
  push:
    branches: [ "pipeline" ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and deploy to Azure"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  translate_dict:
    runs-on: ubuntu-latest
    name: Translate dictionary to German
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy translation service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: openarabdict
          template: ./infrastructure/translator.bicep
          failOnStdErr: false
          
      - name: Azure CLI Action
        uses: Azure/cli@v2.2.0
        with:
          inlineScript: az resource delete --resource-group openarabdict
