name: Translate dictionary to German

on:
  push:
    branches: [ "pipeline" ] #TODO: REMOVE THIS!
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and deploy to Azure"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  translate_dict:
    runs-on: ubuntu-latest
    name: Translate dictionary to German
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      #TODO: compile translation service

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download English dictionary #TODO: REMOVE THE COPY!
        run: |
          az storage blob download --file ./en.json --blob-url https://openarabdictdbstorage.blob.core.windows.net/dbstorage/db.json --auth-mode login --overwrite
          cp ./en.json ./de.json
        working-directory: ./

      - name: Deploy translation service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: openarabdict
          template: ./infrastructure/translator.bicep
          failOnStdErr: false

      #TODO call translation service
          
      - name: Azure CLI Action
        uses: Azure/cli@v2.2.0
        with:
          inlineScript: az resource delete --resource-group openarabdict --resource-type Microsoft.CognitiveServices/accounts --name openarabdict-translator

      - name: Upload dict to Azure
        run: |
          az storage blob upload --file ./de.json --blob-url https://openarabdictdbstorage.blob.core.windows.net/dbstorage/de.json --auth-mode login --overwrite
          az webapp restart --resource-group openarabdict --name openarabdictviewer-backend
        working-directory: ./

      - name: logout
        run: |
          az logout
